name: Build and Release to Gitea

on:
  push:
    tags:
      - 'v*'
    branches:
      - feature/gitea-release-workflow

jobs:
  build-and-release:
    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v4

    - name: Verify dotnet
      shell: pwsh
      run: |
        dotnet --version
        dotnet --list-sdks

    - name: Extract version from code
      id: get_version
      shell: pwsh
      run: |
        $content = Get-Content "TestCSharpDll.cs"
        $major = ($content | Select-String 'about\.VersionMajor = (\d+)').Matches.Groups[1].Value
        $minor = ($content | Select-String 'about\.VersionMinor = (\d+)').Matches.Groups[1].Value
        $revision = ($content | Select-String 'about\.Revision = (\d+)').Matches.Groups[1].Value
        $version = "$major.$minor.$revision"
        Write-Host "Detected version: $version"
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Restore dependencies
      shell: pwsh
      run: dotnet restore

    - name: Build
      shell: pwsh
      run: dotnet build --configuration Release --no-restore

    - name: Create Gitea Release
      uses: akkuman/gitea-release-action@v1
      with:
        files: |-
          bin/Release/net8.0-windows/mb_MQTT.dll
        name: v${{ steps.get_version.outputs.version }}
        tag_name: v${{ steps.get_version.outputs.version }}
